# =======================
# HousingPlugin Config
# =======================
# Prefix used for all plugin messages.
# =======================
prefix: "§x§A§2§8§B§5§9§lʜ§x§A§4§8§D§5§A§lᴏ§x§A§5§8§E§5§C§lᴜ§x§A§7§9§0§5§D§lꜱ§x§A§9§9§1§5§E§lɪ§x§A§A§9§3§6§0§lɴ§x§A§C§9§4§6§1§lɢ §8» §f"

# =======================
# Messages
# =======================
# Messages shown in chat.
# =======================
messages:
  commands:
    permissions:
      no-permission: "&cʏᴏᴜ ᴅᴏɴ’ᴛ ʜᴀᴠᴇ ᴘᴇʀᴍɪꜱꜱɪᴏɴ ᴛᴏ ᴜꜱᴇ ᴛʜɪꜱ."
      not-a-player: "&cᴏɴʟʏ ᴘʟᴀʏᴇʀꜱ ᴄᴀɴ ᴅᴏ ᴛʜᴀᴛ."
      player-not-found: "&cᴘʟᴀʏᴇʀ &e%player% &cɴᴏᴛ ꜰᴏᴜɴᴅ!"
      invite-player-you: "&cʏᴏᴜ ᴄᴀɴ’ᴛ ɪɴᴠɪᴛᴇ ʏᴏᴜʀꜱᴇʟꜰ."
      housing-not-found: "&cʜᴏᴜꜱɪɴɢ ꜰᴏʀ &e%player% &cɴᴏᴛ ꜰᴏᴜɴᴅ!"
      not-in-own-housing: "&cʏᴏᴜ ᴀʀᴇɴ’ᴛ ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
      no-housing: "&cʏᴏᴜ ᴅᴏɴ'ᴛ ʜᴀᴠᴇ ᴀ ʜᴏᴜꜱɪɴɢ!"
      no-housings: "&cᴛʜᴇʀᴇ ᴀʀᴇ ɴᴏ ʜᴏᴜꜱɪɴɢꜱ ᴀᴠᴀɪʟᴀʙʟᴇ!"
      player-not-in-housing: "&cᴘʟᴀʏᴇʀ ɪꜱɴ'ᴛ ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ!"
    reload:
      reload-success: "&aᴄᴏɴꜰɪɢ ʀᴇʟᴏᴀᴅᴇᴅ!"
    create:
      create-usage: "&cᴜꜱᴇ: /housing create <ɴᴀᴍᴇ>"
      housing-created: "&aʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ ᴡᴀꜱ ᴄʀᴇᴀᴛᴇᴅ!"
      already-has-housing: "&cʏᴏᴜ ᴀʟʀᴇᴀᴅʏ ʜᴀᴠᴇ ᴀ ʜᴏᴜꜱɪɴɢ!"
    delete:
      no-housing-to-delete: "&cʏᴏᴜ ᴅᴏɴ’ᴛ ʜᴀᴠᴇ ᴀ ʜᴏᴜꜱɪɴɢ ᴛᴏ ᴅᴇʟᴇᴛᴇ!"
      housing-deleted: "&aʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ ᴡᴀꜱ ᴅᴇʟᴇᴛᴇᴅ!"
    invite:
      invite-usage: "&cᴜꜱᴇ: /housing invite <ᴘʟᴀʏᴇʀ>"
      already-invited: "&cʏᴏᴜ’ᴠᴇ ᴀʟʀᴇᴀᴅʏ ɪɴᴠɪᴛᴇᴅ &e%player%&c!"
      invite-received: "&aʏᴏᴜ ʜᴀᴠᴇ ʙᴇᴇɴ ɪɴᴠɪᴛᴇᴅ ᴛᴏ ᴀ ʜᴏᴜꜱɪɴɢ! &eᴄʟɪᴄᴋ &7ᴛᴏ ᴊᴏɪɴ."
      invite-sent: "&aɪɴᴠɪᴛᴇ sᴇɴᴛ ᴛᴏ &e%player%&a!"
      cannot-invite-self: "&cʏᴏᴜ ᴄᴀɴ’ᴛ ɪɴᴠɪᴛᴇ ʏᴏᴜʀꜱᴇʟꜰ."
    join:
      join-usage: "&cᴜꜱᴇ: /housing join <ᴘʟᴀʏᴇʀ>"
      joined-housing: "&aʏᴏᴜ ᴊᴏɪɴᴇᴅ &e%player%'ꜱ &aʜᴏᴜꜱɪɴɢ!"
    kick:
      kick-usage: "&cᴜꜱᴇ: /housing kick <ᴘʟᴀʏᴇʀ> [ʀᴇᴀꜱᴏɴ]"
      player-kicked: "&aʏᴏᴜ ʜᴀᴠᴇ ᴋɪᴄᴋᴇᴅ &e%player% &aꜰʀᴏᴍ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ!"
      you-were-kicked: "&cʏᴏᴜ ʜᴀᴠᴇ ʙᴇᴇɴ ᴋɪᴄᴋᴇᴅ ꜰʀᴏᴍ &e%housing%&c!"
      you-were-kicked-reason: "&cʏᴏᴜ ʜᴀᴠᴇ ʙᴇᴇɴ ᴋɪᴄᴋᴇᴅ ꜰʀᴏᴍ &e%housing%&c! &7ʀᴇᴀꜱᴏɴ: &e%reason%"
      cannot-kick-self: "&cʏᴏᴜ ᴄᴀɴ'ᴛ ᴋɪᴄᴋ ʏᴏᴜʀꜱᴇʟꜰ!"
    ban:
      ban-usage: "&cᴜꜱᴇ: /housing ban <ᴘʟᴀʏᴇʀ> [ʀᴇᴀꜱᴏɴ]"
      player-banned: "&aʏᴏᴜ ʜᴀᴠᴇ ʙᴀɴɴᴇᴅ &e%player% &aꜰʀᴏᴍ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ!"
      you-were-banned: "&cʏᴏᴜ ʜᴀᴠᴇ ʙᴇᴇɴ ʙᴀɴɴᴇᴅ ꜰʀᴏᴍ &e%housing%&c!"
      you-were-banned-reason: "&cʏᴏᴜ ʜᴀᴠᴇ ʙᴇᴇɴ ʙᴀɴɴᴇᴅ ꜰʀᴏᴍ &e%housing%&c! &7ʀᴇᴀꜱᴏɴ: &e%reason%"
      cannot-ban-self: "&cʏᴏᴜ ᴄᴀɴ'ᴛ ʙᴀɴ ʏᴏᴜʀꜱᴇʟꜰ!"
      already-banned: "&e%player% &cɪꜱ ᴀʟʀᴇᴀᴅʏ ʙᴀɴɴᴇᴅ!"
      housing-banned: "&cʏᴏᴜ ᴀʀᴇ ʙᴀɴɴᴇᴅ ꜰʀᴏᴍ ᴛʜɪꜱ ʜᴏᴜꜱɪɴɢ!"
    unban:
      unban-usage: "&cᴜꜱᴇ: /housing unban <ᴘʟᴀʏᴇʀ>"
      player-unbanned: "&aʏᴏᴜ ʜᴀᴠᴇ ᴜɴʙᴀɴɴᴇᴅ &e%player% &aꜰʀᴏᴍ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ!"
      player-not-banned: "&e%player% &cɪꜱ ɴᴏᴛ ʙᴀɴɴᴇᴅ!"
    gamemode:
      gamemode-usage-invalid: "&cɪɴᴠᴀʟɪᴅ ɢᴀᴍᴇᴍᴏᴅᴇ! ᴜꜱᴇ: ᴄʀᴇᴀᴛɪᴠᴇ, ᴀᴅᴠᴇɴᴛᴜʀᴇ, ꜱᴜʀᴠɪᴠᴀʟ."
      gamemode-usage: "&cᴜꜱᴇ: /housing gamemode <ᴄʀᴇᴀᴛɪᴠᴇ|ᴀᴅᴠᴇɴᴛᴜʀᴇ|ꜱᴜʀᴠɪᴠᴀʟ> [ᴘʟᴀʏᴇʀ]"
      gamemode-creative: "&a%player%'ꜱ ɢᴀᴍᴇᴍᴏᴅᴇ ꜱᴇᴛ ᴛᴏ &eᴄʀᴇᴀᴛɪᴠᴇ&a."
      gamemode-adventure: "&a%player%'ꜱ ɢᴀᴍᴇᴍᴏᴅᴇ ꜱᴇᴛ ᴛᴏ &eᴀᴅᴠᴇɴᴛᴜʀᴇ&a."
      gamemode-survival: "&a%player%'ꜱ ɢᴀᴍᴇᴍᴏᴅᴇ ꜱᴇᴛ ᴛᴏ &eꜱᴜʀᴠɪᴠᴀʟ&a."
    time:
      time-usage: "&cᴜꜱᴇ: /housing time <ᴅᴀʏ|ɴɪɢʜᴛ|ᴅᴀᴡɴ|ɴᴏᴏɴ>"
      time-day: "&aᴛɪᴍᴇ ꜱᴇᴛ ᴛᴏ &eᴅᴀʏ&a!"
      time-night: "&aᴛɪᴍᴇ ꜱᴇᴛ ᴛᴏ &eɴɪɢʜᴛ&a!"
      time-dawn: "&aᴛɪᴍᴇ ꜱᴇᴛ ᴛᴏ &eᴅᴀᴡɴ&a!"
      time-noon: "&aᴛɪᴍᴇ ꜱᴇᴛ ᴛᴏ &eɴᴏᴏɴ&a!"
  vote:
    already-voted: "&cʏᴏᴜ ʜᴀᴠᴇ ᴀʟʀᴇᴀᴅʏ ᴠᴏᴛᴇᴅ ꜰᴏʀ ᴛʜɪꜱ ʜᴏᴜꜱɪɴɢ!"
    voted: "&aʏᴏᴜ ʜᴀᴠᴇ ᴠᴏᴛᴇᴅ ꜰᴏʀ %player%'ꜱ ʜᴏᴜꜱɪɴɢ!"
    owner-cannot-vote: "&cʏᴏᴜ ᴄᴀɴɴᴏᴛ ᴠᴏᴛᴇ ꜰᴏʀ ʏᴏᴜʀ ᴏᴡɴ ʜᴏᴜꜱɪɴɢ!"
    owner-cannot-supervote: "&cʏᴏᴜ ᴄᴀɴɴᴏᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇ ꜰᴏʀ ʏᴏᴜʀ ᴏᴡɴ ʜᴏᴜꜱɪɴɢ!"
    super-voted: "&aʏᴏᴜ ʜᴀᴠᴇ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇ ꜰᴏʀ %player%'ꜱ ʜᴏᴜꜱɪɴɢ!"
  toggles:
    break-blocks-denied: "&cʏᴏᴜ ᴄᴀɴ’ᴛ ʙʀᴇᴀᴋ ʙʟᴏᴄᴋꜱ ɪɴ ᴛʜɪꜱ ʜᴏᴜꜱɪɴɢ!"
    place-blocks-denied: "&cʏᴏᴜ ᴄᴀɴ’ᴛ ᴘʟᴀᴄᴇ ʙʟᴏᴄᴋꜱ ɪɴ ᴛʜɪꜱ ʜᴏᴜꜱɪɴɢ!"
    break-blocks-toggled: "&aʙʟᴏᴄᴋ ʙʀᴇᴀᴋɪɴɢ ʜᴀꜱ ʙᴇᴇɴ %status%."
    place-blocks-toggled: "&aʙʟᴏᴄᴋ ᴘʟᴀᴄɪɴɢ ʜᴀꜱ ʙᴇᴇɴ %status%."
    mob-spawning-toggled: "&aᴍᴏʙ ꜱᴘᴀᴡɴɪɴɢ ʜᴀꜱ ʙᴇᴇɴ %status%."
    natural-regeneration-toggled: "&eɴᴀᴛᴜʀᴀʟ ʀᴇɢᴇɴᴇʀᴀᴛɪᴏɴ ʜᴀꜱ ʙᴇᴇɴ %status%."
    default-gamemode-changed: "&aᴅᴇꜰᴀᴜʟᴛ ɢᴀᴍᴇᴍᴏᴅᴇ ᴄʜᴀɴɢᴇᴅ ᴛᴏ %gamemode%."
    pvp-toggled: "&aᴘᴠᴘ ʜᴀꜱ ʙᴇᴇɴ %status%."
    fall-damage-toggled: "&aꜰᴀʟʟ ᴅᴀᴍᴀɢᴇ ʜᴀꜱ ʙᴇᴇɴ %status%."

# =======================
# Sounds
# =======================
# Sounds played on certain events.
# =======================
sounds:
  housing-created: "ENTITY_PLAYER_LEVELUP"
  player-invited: "ENTITY_VILLAGER_TRADE"
  invite-received: "ENTITY_EXPERIENCE_ORB_PICKUP"

# =======================
# GUI Configuration
# =======================
# Settings for the Housing GUI.
# =======================
gui:
  settings:
    break-blocks:
      name: "&aʙʀᴇᴀᴋ ʙʟᴏᴄᴋꜱ"
      lore:
        - "&8» &7ᴀʟʟᴏᴡꜱ ᴍᴇᴍʙᴇʀꜱ ᴛᴏ ʙʀᴇᴀᴋ ʙʟᴏᴄᴋꜱ"
        - "&8» &7ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
        - "&8» &7ꜱᴛᴀᴛᴜꜱ: %status%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴛᴏɢɢʟᴇ!"
    place-blocks:
      name: "&aᴘʟᴀᴄᴇ ʙʟᴏᴄᴋꜱ"
      lore:
        - "&8» &7ᴀʟʟᴏᴡꜱ ᴍᴇᴍʙᴇʀꜱ ᴛᴏ ᴘʟᴀᴄᴇ ʙʟᴏᴄᴋꜱ"
        - "&8» &7ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
        - "&8» &7ꜱᴛᴀᴛᴜꜱ: %status%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴛᴏɢɢʟᴇ!"
    mob-spawning:
      name: "&aᴍᴏʙ ꜱᴘᴀᴡɴɪɴɢ"
      lore:
        - "&8» &7ᴀʟʟᴏᴡꜱ ᴍᴏʙꜱ ᴛᴏ ꜱᴘᴀᴡɴ"
        - "&8» &7ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
        - "&8» &7ꜱᴛᴀᴛᴜꜱ: %status%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴛᴏɢɢʟᴇ!"
    pvp:
      name: "&aᴘᴠᴘ"
      lore:
        - "&8» &7ᴀʟʟᴏᴡꜱ ᴘᴠᴘ ᴄᴏᴍʙᴀᴛ"
        - "&8» &7ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
        - "&8» &7ꜱᴛᴀᴛᴜꜱ: %status%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴛᴏɢɢʟᴇ!"
    fall-damage:
      name: "&aꜰᴀʟʟ ᴅᴀᴍᴀɢᴇ"
      lore:
        - "&8» &7ᴀʟʟᴏᴡꜱ ꜰᴀʟʟ ᴅᴀᴍᴀɢᴇ"
        - "&8» &7ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
        - "&8» &7ꜱᴛᴀᴛᴜꜱ: %status%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴛᴏɢɢʟᴇ!"
    natural-regeneration:
      name: "&aɴᴀᴛᴜʀᴀʟ ʀᴇɢᴇɴᴇʀᴀᴛɪᴏɴ"
      lore:
        - "&8» &7ᴀʟʟᴏᴡꜱ ɴᴀᴛᴜʀᴀʟ ʀᴇɢᴇɴᴇʀᴀᴛɪᴏɴ"
        - "&8» &7ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
        - "&8» &7ꜱᴛᴀᴛᴜꜱ: %status%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴛᴏɢɢʟᴇ!"
    default-gamemode:
      name: "&aᴅᴇꜰᴀᴜʟᴛ ɢᴀᴍᴇᴍᴏᴅᴇ"
      lore:
        - "&8» &7ꜱᴇᴛꜱ ᴅᴇꜰᴀᴜʟᴛ ɢᴀᴍᴇᴍᴏᴅᴇ"
        - "&8» &7ɪɴ ʏᴏᴜʀ ʜᴏᴜꜱɪɴɢ."
        - "&8» &7ᴄᴜʀʀᴇɴᴛ: %gamemode%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ!"
  list:
    name: "&lʜᴏᴜꜱɪɴɢ ʟɪꜱᴛ"
    item:
      lore:
        - "&8» &7ᴏᴡɴᴇʀ: &a%owner%"
        - "&8» &7ꜱᴛᴀᴛᴜꜱ: &a%online_status%"
        - "&8» &7ᴘʟᴀʏᴇʀꜱ: &a%player_count%"
        - "&8» &7ᴍᴇᴍʙᴇʀꜱ: &a%members_count%"
        - "&8» &7ᴠᴏᴛᴇꜱ: &a%votes%"
        - "&8» &7ꜱᴜᴘᴇʀᴠᴏᴛᴇꜱ: &a%super_votes%"
        - ""
        - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴊᴏɪɴ ᴛʜɪꜱ ʜᴏᴜꜱɪɴɢ!"
        - "&eʀɪɢʜᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴠᴏᴛᴇ ꜰᴏʀ ᴛʜɪꜱ ʜᴏᴜꜱɪɴɢ!"
    next-page:
      name: "&aɴᴇxᴛ ᴘᴀɢᴇ"
      item:
        lore:
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ɢᴏ ᴛᴏ ɴᴇxᴛ ᴘᴀɢᴇ."
    previous-page:
      name: "&aᴘʀᴇᴠɪᴏᴜꜱ ᴘᴀɢᴇ"
      item:
        lore:
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ɢᴏ ᴛᴏ ᴘʀᴇᴠɪᴏᴜꜱ ᴘᴀɢᴇ."
    page-info:
      material: "PAPER"
      name: "&aᴘᴀɢᴇ %page%/%total_pages%"
      lore:
        - "&8» &7ᴀʟʟ ʜᴏᴜꜱɪɴɢꜱ: &a%total_houses%"
    sort-modes:
      default:
        name: "&aᴅᴇꜰᴀᴜʟᴛ ꜱᴏʀᴛ"
        lore:
          - "&7ꜱᴏʀᴛᴇᴅ ʙʏ ᴅᴇꜰᴀᴜʟᴛ ᴏʀᴅᴇʀ."
          - ""
          - "&8» &aᴅᴇꜰᴀᴜʟᴛ ꜱᴏʀᴛ"
          - "&8» &7ᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ᴀʟᴘʜᴀʙᴇᴛɪᴄᴀʟ"
          - "&8» &7ᴍᴏꜱᴛ ᴠᴏᴛᴇꜱ"
          - "&8» &7ᴍᴏꜱᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ"
          - ""
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴅᴏᴡɴ."
          - "&eʀɪɢʜᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴜᴘ."
      most_players:
        name: "&aᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ"
        lore:
          - "&7ꜱᴏʀᴛᴇᴅ ʙʏ ᴛʜᴇ ɴᴜᴍʙᴇʀ ᴏꜰ ᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ."
          - ""
          - "&8» &7ᴅᴇꜰᴀᴜʟᴛ ꜱᴏʀᴛ"
          - "&8» &aᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ᴀʟᴘʜᴀʙᴇᴛɪᴄᴀʟ"
          - "&8» &7ᴍᴏꜱᴛ ᴠᴏᴛᴇꜱ"
          - "&8» &7ᴍᴏꜱᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ"
          - ""
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴅᴏᴡɴ."
          - "&eʀɪɢʜᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴜᴘ."
      least_players:
        name: "&aʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ"
        lore:
          - "&7ꜱᴏʀᴛᴇᴅ ʙʏ ᴛʜᴇ ɴᴜᴍʙᴇʀ ᴏꜰ ʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ."
          - ""
          - "&8» &7ᴅᴇꜰᴀᴜʟᴛ ꜱᴏʀᴛ"
          - "&8» &7ᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &aʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ᴀʟᴘʜᴀʙᴇᴛɪᴄᴀʟ"
          - "&8» &7ᴍᴏꜱᴛ ᴠᴏᴛᴇꜱ"
          - "&8» &7ᴍᴏꜱᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ"
          - ""
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴅᴏᴡɴ."
          - "&eʀɪɢʜᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴜᴘ."
      alphabetical:
        name: "&aᴀʟᴘʜᴀʙᴇᴛɪᴄᴀʟ"
        lore:
          - "&7ꜱᴏʀᴛᴇᴅ ʙʏ ʜᴏᴜꜱɪɴɢ’ꜱ ɴᴀᴍᴇ."
          - ""
          - "&8» &7ᴅᴇꜰᴀᴜʟᴛ ꜱᴏʀᴛ"
          - "&8» &7ᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &aᴀʟᴘʜᴀʙᴇᴛɪᴄᴀʟ"
          - "&8» &7ᴍᴏꜱᴛ ᴠᴏᴛᴇꜱ"
          - "&8» &7ᴍᴏꜱᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ"
          - ""
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴅᴏᴡɴ."
          - "&eʀɪɢʜᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴜᴘ."
      most_votes:
        name: "&aᴍᴏꜱᴛ ᴠᴏᴛᴇꜱ"
        lore:
          - "&7ꜱᴏʀᴛᴇᴅ ʙʏ ᴛʜᴇ ɴᴜᴍʙᴇʀ ᴏꜰ ᴠᴏᴛᴇꜱ."
          - ""
          - "&8» &7ᴅᴇꜰᴀᴜʟᴛ ꜱᴏʀᴛ"
          - "&8» &7ᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ᴀʟᴘʜᴀʙᴇᴛɪᴄᴀʟ"
          - "&8» &aᴍᴏꜱᴛ ᴠᴏᴛᴇꜱ"
          - "&8» &7ᴍᴏꜱᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ"
          - ""
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴅᴏᴡɴ."
          - "&eʀɪɢʜᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴜᴘ."
      most_super_votes:
        name: "&aᴍᴏꜱᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ"
        lore:
          - "&7ꜱᴏʀᴛᴇᴅ ʙʏ ᴛʜᴇ ɴᴜᴍʙᴇʀ ᴏꜰ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ."
          - ""
          - "&8» &7ᴅᴇꜰᴀᴜʟᴛ ꜱᴏʀᴛ"
          - "&8» &7ᴍᴏꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ʟᴇᴀꜱᴛ ᴘʟᴀʏᴇʀꜱ"
          - "&8» &7ᴀʟᴘʜᴀʙᴇᴛɪᴄᴀʟ"
          - "&8» &7ᴍᴏꜱᴛ ᴠᴏᴛᴇꜱ"
          - "&8» &aᴍᴏꜱᴛ ꜱᴜᴘᴇʀ ᴠᴏᴛᴇꜱ"
          - ""
          - "&eʟᴇꜰᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴅᴏᴡɴ."
          - "&eʀɪɢʜᴛ-ᴄʟɪᴄᴋ ᴛᴏ ᴄʏᴄʟᴇ ᴜᴘ."
    random-housing:
      name: "&bʀᴀɴᴅᴏᴍ ʜᴏᴜꜱɪɴɢ"
      lore:
        - "&7ᴄʟɪᴄᴋ ᴛᴏ ᴊᴏɪɴ ᴀ ʀᴀɴᴅᴏᴍ ʜᴏᴜꜱɪɴɢ!"
      skull-owner: "MHF_Question"

# =======================
# Scoreboard Configuration
# =======================
# Scoreboard configuration.
# =======================
scoreboard:
  title: "&a%name%"
  lines:
    - "&8» &7ᴏᴡɴᴇʀ: &a%owner%"
    - "&8» &7ᴠᴏᴛᴇꜱ: &a%votes%"
    - "&8» &7ꜱᴜᴘᴇʀᴠᴏᴛᴇꜱ: &a%super_votes%"
    - "&8» &7ᴘʟᴀʏᴇʀꜱ: &a%player_count%"
    - "&8» &7ᴍᴇᴍʙᴇʀꜱ: &a%members_count%"

# =======================
# Chat Configuration
# =======================
# Chat configuration.
# =======================
chat:
  format: "%rank% &f%player% &8» &r%message%"
  default-rank: ""
  ranks:
    owner: "&4Owner"
    member: "&7Member"
